### ISSUE TITLE
Loading locks when reset pressed after boot

### ISSUE THREAD

**Issue by AlexRast** [SpiNNakerManchester/SpiNNakerManchester.github.io#4] opened 2015-06-17 14:36 UTC
If you start a simulation, where SpiNNMan boots the board and checks it's booted, and then press reset on the board before the simulation starts loading, the load step locks. No timeout. Not an urgent bug but noted for the record.

**Comment by alan-stokes** [comment] 2015-08-13 09:55
I cannot reproduce the problem with the current version of the software. Im going to close the issue, but please reopen it if it continues.

**Closed as completed by alan-stokes** 2015-08-13 09:55 UTC

**Comment by AlexRast** [comment] 2015-08-13 14:26
I think this is an old problem that was (probably) fixed inadvertently months 
ago in some revision or another. I have not seen this problem for a while.

**Comment by alan-stokes** [comment] 2015-08-13 15:51
you often boot your board with the tool chain and then reset it during its exeuction? _eye brow raise_
